### ISSUE TITLE
No, seriously!

### ISSUE THREAD

**Issue by skynet** [astronomerio/analytics-php#2]
You are using an outdated library from Segment. Why?

**Comment by thisisamurray** [comment]
Hey @skynet, there isn't a specific reason why this library is outdated. We've gotten behind on keeping up with Segment's changes as we focused on a few parts of our own platform. Currently working on updating all of our forked Segment libraries over the next month to get them all up to the latest, including this one.

**Comment by ryw** [comment]
Just updated w/ Segment latest :)

**Comment by skynet** [comment]
Thanks so much!
